### PR TITLE
#511 - OCR deeds in recent edits for collection

### PR DESCRIPTION
**Pull request by tbl73**

### CODE REVIEW

**Comment by saracarl** [comment]
spec tests didn't work, need to look into it.

**Comment by saracarl** [comment]
try changing test.rb env file to what Trisha is sending me to get Spec tests to work.

**Comment by saracarl** [comment]
spec test worked.  test.rb will show up downstream in one of the other PRs, so not checking in the new test.rb.

**Comment by tbl73** [comment]
Where are you referring to when you mention the leaderboard?

**Comment by saracarl** [comment]
Bottom of this page:

http://fromthepage.com/statistics/collection?collection_id=1

Sara

**Comment by tbl73** [comment]
Now that I look at this again, I'm not sure that information is being
included. The correction information is included in the statistics at the
top of the page, but I'm not sure it is being included in the leaderboard.
Should it have it's own section?  Or be rolled into transcribers or
editors?  (Or replace transcribers?)

**Comment by saracarl** [comment]
Discussed with @benwbrum  We think we should just not worry about it for
now.   If we ever do it, we'll make it the equivalent of a transcription
task in the transcription leaderboard.  (The challenge is that OCR
correction is at a work level --  a collection could have transcriptions
and OCR corrections both.)

**Pull request merged**
