### PR TITLE
Mark pages a needs review - #502, #506, #518

### PR DESCRIPTION
**Pull request by tbl73**
This includes #502, #506, and #518.  In addition, we're now using the status and (new) translation_status fields to track the state of a page.  The possible states are nil, blank, review, transcribed (or translated), and indexed, for either the transcription or translation of a page.  Work statistics are based off those states.  We also switch out the statistics/progress bar depending on whether the work is a transcription or translation work.

### CODE REVIEW

**Comment by saracarl** [comment]
Ok, found a problem.  

To reproduce on a recent production DB:  
http://localhost:3000/display/read_work?page=2&work_id=308
Mark the first 2 pages as blank
then we get to 100% transcribed, but only 75% indexed, even though all the transcribed pages have subject indexes on them.  Blank needs to count as indexed.

**Comment by saracarl** [comment]
What's the right behavior if a page is marked both blank and needs review?  (Did we discuss that?)  We're treating it as "blank" rather than "needs review", but I suspect it should be the opposite.  (Treat it as "needs review" until they uncheck that box.)

**Comment by tbl73** [comment]
I switched the blank pages to being included as indexed pages.  (I think they were removed from indexed sometime early in the process because they ended up being double-counted in those calculations, before the latest iteration of the statistics.)
On the blank and needs review, I think we discussed it and decided to make blank the priority, but it makes to set it to needs review instead, so I changed that.  The "blank" wording won't show up, because it's marked for review rather than as blank.

**Comment by saracarl** [comment]
One more change here -- When a page is marked blank and saved, the checkbox in the UI switches to "page is not blank".  I prefer that it stays at "page is blank" with a check next to it.  It's clearer.

**Comment by saracarl** [comment]
Is there any way we can toggle the "needs review" and "blank" checkboxes in the UI, i.e. so when you check "needs review" it unchecks "mark page as blank" and when you check "mark page as blank" it unchecks "needs review"?

That would be a much clearer view of what is happening under the covers.

**Comment by tbl73** [comment]
I think they can both be done, although it may take me a little bit.  Certainly keeping the checkbox can. That's actually more complicated than it sounds, but it's similar enough to the needs review one.  In terms of toggling, I probably can do something with jquery, but will need to investigate a bit.

**Comment by saracarl** [comment]
Can you open new issues for those 2 (assign them to yourself, and put them in the ready pile so we get to them sooner rather than later)?   I'm going shipping with these small UI issues as long as we improve them shortly.

**Pull request merged**
