### PR TITLE
Text Overlay: Library Upgrades, Automatic Font Size

### PR DESCRIPTION
**Pull request by rsimon**
## In this PR

This PR addresses issues #3976, by upgrading the following files:

- `app/assets/javascripts/annotorious/annotorious-openseadragon.js`
- `app/assets/javascripts/annotorious/annotorious-openseadragon.js.map`
- `app/assets/javascripts/annotorious/annotorious-openseadragon-textlayer.js`
- `app/assets/javascripts/annotorious/annotorious-openseadragon-textlayer.js.map`
- `app/assets/stylesheets/annotorious/annotorious-openseadragon.css`
- `app/assets/stylesheets/annotorious/annotorious-openseadragon-textlayer.css`

The main addition is in the __Annotorious TextLayer plugin__: when loading an ALTO file, the plugin now records the average line height, and sets the font size for the overlay automatically.

For reference: key code changes are here:
- https://github.com/annotorious/annotorious-v3-extensions/commit/099e6e9a630e8fba5b9a9f6335a0c977ddd8bb67
- https://github.com/annotorious/annotorious-v3-extensions/commit/1829a67826a2ed053ae5e77b90dbb9932dc90ab8

### CODE REVIEW

**Comment by benwbrum** [comment]
Trying to integrate this, I run into this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'createImageAnnotator')
    at annotorious-openseadragon.debug-e6e7a96e368a11aba907e0dc54256891b73568fe40a9e1a25d59c8f3e7355316.js:1558:40106
    at annotorious-openseadragon.debug-e6e7a96e368a11aba907e0dc54256891b73568fe40a9e1a25d59c8f3e7355316.js:1:285
    at annotorious-openseadragon.debug-e6e7a96e368a11aba907e0dc54256891b73568fe40a9e1a25d59c8f3e7355316.js:1:344
```

My include statements:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/openseadragon/3.0.0/openseadragon.min.js"></script>
<script src="/assets/openseadragon-filtering.debug-4e77bc9ca7f21601eedee05156aae94a73c784065427535d0f7f70325afe37cb.js"></script>
<script src="/assets/annotorious/annotorious-openseadragon.debug-e6e7a96e368a11aba907e0dc54256891b73568fe40a9e1a25d59c8f3e7355316.js"></script>
<script src="/assets/annotorious/annotorious-openseadragon-textlayer.debug-e2d9a045f7152016a58d35d2a0ed5dbdab42438d48625aa56bc9c34a260b9c1a.js"></script>
```

My initialization:
```

        var anno = OpenSeadragon.Annotorious(viewer);
```

**Comment by rsimon** [comment]
Ah - sorry. Tiny bit might have changed. The init should now be

```
var anno = AnnotoriousOSD.createOSDAnnotator(viewer, {
  pointerSelectAction: 'NONE',
  style: { 
    return { fillOpacity: 0 }
  }     
}
```

Will test this. (Sorry on my phone right now... ;-)

**Comment by rsimon** [comment]
Can you point me to the page template where you are seeing this? Something's wrong with your setup. `createImageAnnotator` should never get called anywhere. And this init line `var anno = OpenSeadragon.Annotorious(viewer)` would have been for the previous version of Annotorious, not the one you are using.

**Comment by rsimon** [comment]
Yikes... it looks like some recent config changes on Annotorious had broken the build for `<script>` imports. (*sigh* JavaScript build hell...) I got the same error as you. I'll have to figure out how to _cleanly_ fix this some other time. But that's another story ;-)

As for this PR: I made another commit. This adds fixed & working versions of `annotorious-openseadragon.js` and `annotorious-openseadragon.js.map`. The error was gone after switching to these files. Let me know if it works on your end, too.

For reference, here's my init code in full. (As you can see, the way the style is declared for Annotorious has changed minimally.)

```js
var viewer = OpenSeadragon({
  id: 'openseadragon',
  prefixUrl: 'https://cdn.jsdelivr.net/npm/openseadragon@3.1/build/openseadragon/images/', 
  gestureSettingsMouse: {
    clickToZoom: false
  },
  gestureSettingsTouch: {
    pinchRotate: true
   },
   tileSources: [{
     type: 'image',
     url: '33054-000002-0001.jpg'
   }]        
 });

 var anno = AnnotoriousOSD.createOSDAnnotator(viewer, {
   pointerSelectAction: 'NONE',
   style: {
     fillOpacity: 0,
     strokeOpacity: 0
   }
 });

 var textlayer = OSDTextLayer.mountExtension(anno, {
   label: OSDTextLayer.transcriptionLabel,
   mode: 'fixedPageSize',
   position: 'center',
   offsetY: 50
});

textlayer.loadOCR('alto-sample.xml');
```

**Comment by benwbrum** [comment]
This looks great!

**Comment by rsimon** [comment]
Phew.... relieved to hear it :-) Sorry for the extra hassle! I'll look into #3351 next.

**Pull request merged**
