### PR TITLE
Restructure zip export for #2136 use original filename for #2811

### PR DESCRIPTION
**Pull request by benwbrum**

### CODE REVIEW

**Comment by saracarl** [comment]
This configuration:
image
Has the following issues:

1. We include folders for each work (the "old" way), and they appeared first in my zip file, which confused me, since they weren't what I asked for and they were empty.  We need to remove the work-folders if you request format level exports.
2.  We need a readme for type of exports.  I asked for work level html exports, organized by format.  I got 3!
image
3.  The html_full export looks correct -- it has versions with contributors & dates, linked subjects, and subject articles.  
4. The html_text export is transcripts, links subjects, and has subject articles.  Seems reasonable, but I'm not sure what was intended.
5. The html_transcript export does not include contributors/versions or subject articles, but *does* link the subjects (the links go to an anchor that doesn't exist in this file).  This is wrong.

**Comment by saracarl** [comment]
We need to make sure this doesn't close issue #2811 because there are a number of separate changes there that aren't part of this PR.

**Comment by saracarl** [comment]
passing tests.
the pdf export metadata has "in scope: true" listed, even though I didn't mess with the "additional metadata".  That seems like a bug, but outside of this.  Opening a new issue.

**Comment by benwbrum** [comment]
Passing tests locally.  The directory restructuring has been fixed.

**Pull request merged**
