### PR TITLE
#2095 Include page counts on subject browse

### LINKED ISSUE #2095: Include page counts on subject browse
> been talking about product features we would be interested in. We are working with our subjects and it would be really helpful to be able to see the number of pages that each term appears on when browsing the list subjects, perhaps as a small gray number next to the term. This would help the causal researcher figure out who among our 800+ people might be interesting and/or important.

### PR DESCRIPTION
**Pull request by symmetrically**
Closes #2095

### CODE REVIEW

**Comment by benwbrum** [comment]
The UI for this looks very good, but the performance is too slow for large projects.

If I log in as owner `petelin` then visit http://localhost:3000/cwrgm/cwrgm-rev2/subjects the page takes five minutes to load; most of which is spent executing SQL queries to find the page count for each subject.

`Completed 200 OK in 318310ms (Views: 267481.2ms | ActiveRecord: 48510.1ms | Allocations: 104765563)`

**Comment by benwbrum** [comment]
Functionality and performance are great.  Could we modify the UI so that the number of pages is displayed next to the subject, in parentheses, but still in the grey color?

**Comment by benwbrum** [comment]
Let's abandon the column spacing and add the parenthetical page counts directly after the subject titles.

**Comment by symmetrically** [comment]
@benwbrum If we abandon the column spacing, Then, it will look weird in context of UI because the Subject titles can be varied in length. Look at below screenshot.

As we are using that span in `Link_to` of subject title
image (98)

**Comment by saracarl** [comment]
Dropping in 2 screenshots of the earlier layout for comparison.
Screenshot from 2023-11-16 10-33-51
Screenshot from 2023-11-16 10-42-20

**Comment by saracarl** [comment]
@symmetrically could we do the link_to *inside* the span, with the page count immediately afterwards with only a space separating it?  
Like this, more or less:

[Newspapers](url) (80)

**Review by saracarl — CHANGES_REQUESTED** [review]
See earlier UI comments.

**Pull request merged**
