### PR TITLE
dashboard: make titles clickable

### PR DESCRIPTION
**Pull request by diegoviola**
This improves on #1447 and #1484 by actually making titles clickable.

Fixes: #1447.

### CODE REVIEW

**Comment by saracarl** [comment]
Can we collapse the sections?  This doesn't add much when the sections are expanded to start with.

Also, can we change "An IIIF Manifest" to "A IIIF Manifest", please?

**Comment by saracarl** [comment]
So if you load this page it starts out "expanded" (all sections open) and then immediately flips to closed/hidden.  Is there any way to start with them all closed?  This will make customers say "what just happened?"

**Comment by saracarl** [comment]
If we're starting with the default (open) style, then have JS that closes the divs when the page loads, that can cause a flicker.  If we can start with the closed style by default, that would avoid the flicker.

**Comment by diegoviola** [comment]
> If we're starting with the default (open) style, then have JS that closes the divs when the page loads, that can cause a flicker. If we can start with the closed style by default, that would avoid the flicker.

I tested it and noticed the flicker, thanks for letting me know.

Hiding the sections with CSS seems to avoid the flicker somehow, please let me know if the latest commits fixes the issue for you as well.

**Comment by saracarl** [comment]
This looks good, but it's no longer passing tests because the tests can't see the div to upload in (I think).  Let's fix those.

**Pull request merged**
