### PR TITLE
#211 last 7 days index stat

### PR DESCRIPTION
**Pull request by tbl73**

### CODE REVIEW

**Comment by saracarl** [comment]
When I tested this for a collection, the "references" count was updated, but "pages indexed" was not.  I was working on a work that had some things indexed, but went to a page that did not have anything indexed and auto-indexed it.  I would have expected the "pages indexed" for "last 7 days" to increment by one.

**Comment by tbl73** [comment]
I used an existing statistic to display that the "pages indexed" number -
I'll have to look more closely at what it's actually doing.

**Comment by tbl73** [comment]
Can you test it again?  I tried in a couple of collections, both with things indexed and not, and the count seems to be incrementing correctly for me.  (I also tried pulling down the code into a branch, and it still seemed fine.)

**Comment by saracarl** [comment]
This is still flaky, for reasons I don't get.  If you look at the attached screenshot you'll see that the "overall" transcribe count is 1, and there's no way when you look at the status of each document that that is correct.

bad_transcribe_count

Not to mention the transcribe count is for last seven days.

I think that maybe we aren't counting some set of pages, and if I index one of those pages, it doesn't get counted in the index statistic either.  (Theory, I can't prove that.)

**Pull request merged**
