### PR TITLE
Added collection, work, and document set slug validation for #2328

### PR DESCRIPTION
**Pull request by sylvieed**
_Resolves #2328_

Previously, the input for slugs/URLs for collections and works had no validation and could be set as just numbers, which causes problems.

Now, when a user tries to save an invalid slug (that has no letters in it, via the regex expression `/[[:alpha:]]/`), an error message will show and the slug will not save.

On the collection page:
collection slug validation

On the work page:
work slug validation

There's also a couple of changes related to #2995 (subject linking enabled) that were necessary to get this working.

### CODE REVIEW

**Comment by benwbrum** [comment]
We need to add slug validation to the `document_set` model as well.

**Comment by sylvieed** [comment]
Slug validation is now added to `document_set`s

**Comment by saracarl** [comment]
I'm not sure what's going on, but when I test a document set with a number I get:
```ActionView::MissingTemplate at /document_sets/public-tcdl-set
Missing template document_sets/edit, application/edit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :slim]}. Searched in:
  * "/home/saracarl/dev/products/fromthepage/fromthepage/app/views"
  * "/home/saracarl/.rvm/gems/ruby-2.7.1/gems/devise-4.8.0/app/views"
  * "/home/saracarl/.rvm/gems/ruby-2.7.1/gems/actiontext-6.0.3.2/app/views"
  * "/home/saracarl/.rvm/gems/ruby-2.7.1/gems/actionmailbox-6.0.3.2/app/views"
  ```
  
 this is from line 69 of the document_set_controller.rb.

@sylvieed would you test this in your environment?  (Do you have any document sets?)  I'll go test in the dev branch to see if this was introduced or already there.

**Comment by saracarl** [comment]
On the development branch it worked fine (other than taking a number!).  Here's where I'm testing; the document set settings view:  `http://localhost:3000/saracarl/public-tcdl-set/settings`

**Comment by sylvieed** [comment]
The document slug validation works now:

document set slug validation

However, some slugs that pass validation are causing issues -- if the slug is `1a23` or `1test` (but `2test` is ok), when trying to access the document set (`/sylvied/1a23`) I get a `404` page.

Should I open a separate issue for this?

**Pull request merged**
