### PR TITLE
transcribe: replace zoomer with openseadragon

### PR DESCRIPTION
**Pull request by diegoviola**
Fixes: #1531

### CODE REVIEW

**Comment by saracarl** [comment]
I'm not getting zoom or pan persistence when I test this.
Reproduce:  Open a IIIF image based work.  Zoom in to the top right.  Save transcript.
Result:  Page reloads at the full page image.  

If I use an uploaded image, the same thing happens.

**Comment by saracarl** [comment]
Good News:  IIIF zoom is persisted.
Bad News:  I found another scenario that doesn't persist correctly.  Try a field based transcription project that uses an over/under default view.  My scenario:

Zoom to this:

Screenshot from 2019-10-08 20-25-18

Save the transcription and it reloads to this:

Screenshot from 2019-10-08 20-25-36

**Comment by saracarl** [comment]
Another error while testing this.  

To reproduce:
(uploaded PDF, field based transcription, over/under view)
On a transcribe page, zoom in on the page.  hit the "preview" button.  hit the "edit" button.  Use the arrows to navigate to the previous or next page.

You get this error:

ArgumentError at /transcribe/save_transcription
When assigning attributes, you must pass a hash as an argument.

TranscribeController#save_transcription
app/controllers/transcribe_controller.rb, line 100

**Comment by diegoviola** [comment]
> Another error while testing this.
> 
> To reproduce:
> (uploaded PDF, field based transcription, over/under view)
> On a transcribe page, zoom in on the page. hit the "preview" button. hit the "edit" button. Use the arrows to navigate to the previous or next page.
> 
> You get this error:
> 
> ArgumentError at /transcribe/save_transcription
> When assigning attributes, you must pass a hash as an argument.
> 
> TranscribeController#save_transcription
> app/controllers/transcribe_controller.rb, line 100

This is a different issue.

**Pull request merged**
