### PR TITLE
Field based transcription - #870, #873, #876

### PR DESCRIPTION
**Pull request by tbl73**

### CODE REVIEW

**Comment by saracarl** [comment]
This is looking good.  Couple of bugs:

1)  "Add new line" isn't working.
2) Selects aren't displaying as a dropdown anymore.

**Comment by tbl73** [comment]
I need more details about what you're seeing, because both of those things are working in my test environment.

**Comment by saracarl** [comment]
Add new line:

Started GET "/transcription_field/line_form" for 127.0.0.1 at 2018-01-03 10:27:31 -0600
Processing by TranscriptionFieldController#line_form as */*
  [1m[36mPageBlock Load (0.1ms)[0m  [1mSELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'transcription_field' AND `page_blocks`.`view` = 'line_form'[0m
  [1m[35mUser Load (0.2ms)[0m  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 4  ORDER BY `users`.`id` ASC LIMIT 1
Completed 500 Internal Server Error in 5ms

NoMethodError (undefined method `next' for nil:NilClass):
  app/controllers/transcription_field_controller.rb:67:in `line_form'


  Rendered /home/saracarl/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.7ms)
  Rendered /home/saracarl/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.0ms)
  Rendered /home/saracarl/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (1.2ms)
  Rendered /home/saracarl/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb (22.9ms)

image

**Comment by saracarl** [comment]
Drop down was my fault -- I was using a comma instead of a semicolon.

**Comment by tbl73** [comment]
Hmm.  That sounds as though the param isn't being passed through the ajax call; maybe it's not finding it in the first place?  I think we'll have to troubleshoot offline.

**Pull request merged**
