### PR TITLE
Add Uploader to Main App

### PR DESCRIPTION
**Pull request by benwbrum**
*Do not merge yet*

This work, based on the ui-design branch, supports the ingesting of new documents to the system.  

# Current Status

The feature allows existing users with existing collections to upload a new file to the system.  It also allows an administrator to run a rake task to process the upload so that it will be ready to run.

## To-Do for the current system

At the moment there's no way in or out of the system, and the standard Rails scaffold actions need to be put behind authorization walls,  To itemize the TODO items:

* Add a link to `new_document_upload` from the Owner Actions (@kolking)
* Style the `views/document_upload/new` view and form (@kolking)
* Redirect an uploaded document to the `show` action: `document_upoad#create` needs `redirect_to collection_path(@document_upload.collection)` in it with a success action saying "Your documents have been uploaded and will be processed shortly.  You'll receive an email at `#{@document_upload.user.email} when the documents are ready." (@kolking)
* Put `document_upload` actions other than `#new` and `#create` behind an authorization filter so that only an administrative user can see those pages. (@benwbrum or @saracarl)
* Add a link to the document_uploads index page to the admin dashboard.   (@benwbrum or @saracarl)

# Second Phase: Automated processing

The create action should fire off the automation itself.

* Call rake on the document upload
* Modify rake task to email end user when the document upload is finished

# Third Phase: New project hooks

The feature should be accessible from "start a new project" for anyone.  This should prompt them to create a new user and new collection.

### CODE REVIEW

**Comment by kolking** [comment]
@benwbrum when user upload a document, is collection required to be set? I mean, can it be blank or not? If it can be blank, then we cannot redirect user to the collection page. In such case I suppose we should redirect him to the dashboard with the same flash message.

One more question. There is a view with the list of all document_uploads (index.html), I think this page should be accessible to admins only - those who will review the uploads. So we should probably place the link to this page in the admin dashboard. Am I right?

**Comment by benwbrum** [comment]
Yes, Nick.  The uploader UI will require a collection to be set to create a
document_upload.  We'll handle the things we discussed about "default
collections" before the user encounters this screen.

I agree -- the document_uploads#index (in fact everything except #new and
#create) should be admin-only.

Ben

**Comment by kolking** [comment]
@benwbrum got it, thanks!

**Comment by kolking** [comment]
@benwbrum is it required for admin to edit existing document_upload to set another collection and file, or admin should be able only to see/delete uploaded documents?

**Comment by benwbrum** [comment]
The admin should only be able to see uploads.  There's not much they can
do, actually -- we should remove the edit/update actions.

Ben

**Comment by kolking** [comment]
@benwbrum It's ready for review.
1) Upload administration is in the admin dashboard, so only admins have access. I guess there should be also some "process upload" action, but for now admin can see the list of user uploads and delete them.
2) Document upload is in the owners dashboard. I've included validation to make sure an existing collection and file are present. After uploading they are redirected to the collection overview page.

**Comment by benwbrum** [comment]
Hooray!  I'll review it tomorrow around 20:30 UTC.

Your description sounds exactly right.

**Comment by benwbrum** [comment]
The UI has been reviewed and looks good.  Waiting to merge for my background task processing work to be finished.

**Pull request merged**
