### PR TITLE
First draft of IIIF v3 import for #1826

### PR DESCRIPTION
**Pull request by benwbrum**

### CODE REVIEW

**Comment by benwbrum** [comment]
To test with before merging:

- [ ] https://iiif.wellcomecollection.org/presentation/v3/b31874058
- [ ] https://data.nhm.ac.uk/iiif/resource/8d76e3e4-bcef-48f3-a32c-b72e2b8b300b/record/386
- [ ] https://lbiiif.riksarkivet.se/arkis!A0069179/manifest


Collection manifests from the Swedish National Archives

- [ ] https://lbiiif.riksarkivet.se/collection/riksarkivet
- [ ] https://lbiiif.riksarkivet.se/collection/amnesomraden
- [ ] https://lbiiif.riksarkivet.se/collection/tid
- [ ] https://lbiiif.riksarkivet.se/collection/arkiv/lZkyF37hGIL2wcbGB1Vju6

**Comment by saracarl** [comment]
This manifest fails import:
https://data.nhm.ac.uk/iiif/resource/8d76e3e4-bcef-48f3-a32c-b72e2b8b300b/record/386
with an `undefined method `first' for nil:NilClass` 
on line 217 of sc_manifest.rb


This manifest fails import:
https://lbiiif.riksarkivet.se/arkis!A0069179/manifest
with an undefined method `sub' for nil:NilClass 
on
https://github.com/benwbrum/fromthepage/blob/main/app/models/sc_canvas.rb#L8

The first collection manifest fails import with a flash message "Please enter a valid IIIF manifest URL."
https://lbiiif.riksarkivet.se/collection/riksarkivet
Which is caused by:
```
undefined method `collection_for_v3_hash' for #<Class:0x000055e556feac68>
Did you mean?  collection_for_at_id

```
This is the same for the 2nd collection URL, so I'm going to hold off testing the rest until we resolve it.

**Review by saracarl — CHANGES_REQUESTED** [review]

**Comment by benwbrum** [comment]
This is ready for re-testing.

We should manually test a CONTENTdm import (including collection level) as well.

**Comment by saracarl** [comment]
Lots of random curly brackets in the metadata on this one:  https://data.nhm.ac.uk/iiif/resource/8d76e3e4-bcef-48f3-a32c-b72e2b8b300b/record/386
image

that's on the import screen, not the "about" page for the work. (Same for 2nd manifest.)

I did find it odd the page title was the image url:
image

Riksarkivet collection import is multilingually ugly:
image

and fails with a ```TypeError at /sc_collections/explore_collection
no implicit conversion of nil into String``` on line 38 of sc_collection.rb
(same issue happens with https://lbiiif.riksarkivet.se/collection/amnesomraden)

**Comment by benwbrum** [comment]
I've fixed the Riksarkivet collection links.  The nhm problem appears to be a non-compliant manifest issue that I think we can punt on.

**Pull request merged**
