### PR TITLE
#2858 Added feature for showing contributions hours view and PDF letter download

### PR DESCRIPTION
**Pull request by symmetrically**

### CODE REVIEW

**Review by benwbrum — COMMENTED** [review]
The code looks good to me!

**Comment by benwbrum** [comment]
I'm not entirely sure what to do about the line breaks with `collec-` -- there are a [handful of options](https://pandoc.org/MANUAL.html) you can pass to Pandoc, so could we explore a bit?

Let's right-justify the `Pages Count` column and rename the header to `Pages`.  That may give us a bit more room for the collection.  (Note that we had to use a special markdown tables plugin when we run Pandoc in the work PDF export, which is passed in as a command-line argument.)

**Review by saracarl — CHANGES_REQUESTED** [review]
Ok.  2 more small changes:
1)  Add a carriage return between the logo and the date.
2)  Make sure it's FromThePage, not FromthePage.  (Branding!)  It's wrong 2 places and correct 1 place.

Otherwise, looks good.

**Review by saracarl — CHANGES_REQUESTED** [review]
Messages are missing:
[letter (2).pdf](https://github.com/benwbrum/fromthepage/files/13427508/letter.2.pdf)

I would probably have added the messages to the dashboard messages file, to match the controller you're using.  With your current setup, you can probably make this work by fully qualifying the message references, i.e. `hours_letter.pdf.letter.certification_text`

We use i18n-tasks to do a lot of this work; it makes it *much* easier.  I'll send an email with some details about that library and our google translate key.  (I probably wouldn't use it with this PR, because it requires starting over, but I would with all the ones in the future.)

**Pull request merged**
