### PR TITLE
#923 - Add email identifier to user select lists

### PR DESCRIPTION
**Pull request by tbl73**

### CODE REVIEW

**Comment by saracarl** [comment]
So the behavior is different on "allowed collaborators" (on a work) and on "add an owner" (on a collection).  the allowed collaborators one works much better than the add an owner one.  Any idea why?

**Comment by tbl73** [comment]
How is the behavior different?  (What does "works much better" mean in this context?)

**Comment by saracarl** [comment]
The filtering works a lot better on collaborators.  If I type "ben" then I get a list of users that match ben in the string.  That doesn't happen on owners.

**Comment by tbl73** [comment]
Huh. I thought that worked for me on owners.  I'll take another look at it.

**Comment by tbl73** [comment]
That's strange - if I try typing Ben into the owners, I get the same users that I get in allowed collaborators, although they are in a different order.  Are you not getting a filtered list at all on owners?

**Comment by tbl73** [comment]
Okay, we figured out that the problem was with field-based transcriptions, which don't offer voice transcriptions.  The jQuery on the field-based settings was looking for a selector that doesn't exist (for voice-based transcription), which was then making the select2 jquery code (that those dropdown boxes use) fail.  I made a couple of changes - see if it's working for you now.

**Comment by saracarl** [comment]
works!  yay!

**Pull request merged**
