### PR TITLE
Landing redesign

### PR DESCRIPTION
**Pull request by saracarl**

### CODE REVIEW

**Comment by techpeace** [comment]
If you ever have any secrets that you'd like to keep out of the public repo, you can `.gitignore` the `.env` file and simply require that it be present when setting up the local dev environment. You can instruct folks to use `.env.example` as a template.

**Comment by saracarl** [comment]
I need to figure out how to keep capistrano from wiping it out in production every time we deploy if we use that path.  (which I agree, would be better.)

**Comment by techpeace** [comment]
Ah, good call - looks like this might do the trick: https://github.com/rjocoleman/capistrano-env-config

**Comment by techpeace** [comment]
Oh nm, that might just be for using `.env` in Capfiles themselves. The other technique I've seen is to hold the production `.env` somewhere outside the deploy directory and copy it in afterward.

**Pull request merged**
