### PR TITLE
Fit image to viewport width on initial load

### PR DESCRIPTION
**Pull request by kolking**
Re #2457 

On initial load we are checking for the previously stored `json_bounds`. If there are saved bounds, we will apply them. If no saved bounds found, we will position the image to fit viewport width, panned to the top.

VERTICAL | HORIZONTAL
---|---
image | image

However, this will happen only once - the very first time they open the Transcribe page in a browser. And after that there always will be `json_bounds` object saved in the local storage, for any other page opened.

I think that maybe we should go further and re-position the image to fit viewport width every time the layout mode changed? So, every time they switch from "Image at the left / right" to "Image at the top / bottom", the image will be re-positioned using the same behavior.

What do you think?

### CODE REVIEW

**Comment by kolking** [comment]
Or, maybe we should save `json_bounds` for a particular page, so zoom + pan applied on the current page won't affect any other page.

**Comment by kolking** [comment]
Or, maybe both - re-position image on every layout change and make each page to have its own `json_bounds` saved in the local storage after user has panned or zoomed.

**Comment by benwbrum** [comment]
Because some documents are scanned with too much empty space, users may zoom in to the useful part of a page, transcribe it, and then move to the next (identically scanned) document.  In that case we don't want them to need to zoom and pan again, so we want `json_bounds` to be kept from page to page.

However, if the user is repositioning their layout, I think it's fair to say that they are modifying the zoom/pan experience and to go to the home/re-positioned image.

So let's ignore `json_bounds` when the layout is changed, but keep it from page to page.

**Comment by kolking** [comment]
I've added the behavior to ignore `json_bounds` and re-position image in the viewport when they change layout mode.

**Review by saracarl — APPROVED** [review]

**Pull request merged**
