### PR TITLE
Simplified owner dashboard and added collection progress bars for #3619

### PR DESCRIPTION
**Pull request by sylvieed**
_Resolves #3619 (and #3590, #3205)_

This improves and simplifies the owner dashboard.

image

### Changes
* UI updated so that collections are more easily distinguished with a border, like how works are shown on the collection show page.
* Collection description removed.
* Works list removed.
* "You can add another work under Start A Project" was previously written under work list, now removed.
* Collection privacy added next to the collection title.
* Document sets nested under the collection they belong to instead of listed at the bottom of the dashboard.
* Inactive collections listed separate from active collections, at the bottom of the dashboard.
* Collection progress % completed statistics added (% completed, transcribed, reviewed, indexed).
* Collection progress bars added.

The logic for these last two statistics are based on the corresponding logic for the work progress bars on the collection show page.

### CODE REVIEW

**Review by saracarl — CHANGES_REQUESTED** [review]
I like this.  Could you also test the UI for when an owner has no collections?  This is the case where an owner is brand new;  I'd like to confirm we still send them to the "Start a Project" once they get the account created, but also that if they end up here there is a message of some sort with a link to Start a Project.

I also restarted the failing tests, since they were failing due to an InternetArchive problem.

**Comment by sylvieed** [comment]
Here's how it looks, this wasn't changed in this PR.
image
It doesn't have a link to the Start a Project page, it links to create a collection. Do you want to change this @saracarl?

**Comment by saracarl** [comment]
Nope, that's fine @sylvieed.  I just wanted to make sure we didn't have regressions that would fail in the common and very important new owner scenario.  

This is great -- I really like how the Active/Inactive headers disappear if you only one of those 2 types.

**Comment by saracarl** [comment]
There's still failing tests, 3 of them.  They are all failing with this because of the UI changes:

>   1) owner actions moves a work to another collection
>      Failure/Error: page.find('.collection-works .collection-work_title').find('a', text: @title).click
>      
>      Capybara::Ambiguous:
>        Ambiguous match, found 4 elements matching visible css ".collection-works .collection-work_title"
>      # ./spec/features/owner_actions_spec.rb:170:in `block (2 levels) in <top (required)>'

**Pull request merged**
