### PR TITLE
Rework image carousel

### PR DESCRIPTION
**Pull request by kolking**
Re #2195, #2083

Here I've changed the carousel plugin because jCarouselLite is quite old and not maintained.
I've switched to the Slick carousel - https://github.com/kenwheeler/slick/

Both issues reported in #2195 and #2083 should be fixed now.

### CODE REVIEW

**Comment by saracarl** [comment]
This is exciting -- I can't wait to test it!

**Review by saracarl — CHANGES_REQUESTED** [review]
This looks great, but it needs some small changes for accessibility.  See in line comments.

(Our customers and open source deployers are large public institutions who are often targeted with lawsuits if their software is not accessible.  If we don't fix this, one of the universities will ask us to in the next 3 months or so.)

**Comment by kolking** [comment]
@saracarl sure, and done. Thanks for pointing me!

Also I wasn't sure about the image size, right now it's limited by 300px (width or height) but if you think the image should be bigger / smaller please let me know.

**Comment by saracarl** [comment]
Thanks!  I like this size.

**Pull request merged**
