### PR TITLE
Issue 323, add work in collection view

### PR DESCRIPTION
**Pull request by tbl73**
Added the ability to add a work directly from the collection page.

### CODE REVIEW

**Comment by saracarl** [comment]
I see "Add Work" on the collection page even if I am not the owner.  You shouldn't see this if you are not an owner.

**Comment by tbl73** [comment]
You just mean the "Add new work" at the bottom of the page, right?  Not the actual tab?  I fixed that and pushed it up.

**Comment by saracarl** [comment]
@tbl73 this now has conflicts due to the wording changes on the previous PR.  Can you merge them and then I'll review it?  Thanks!

**Comment by tbl73** [comment]
I merged ui-design into my local add-work branch, and it didn't seem to have any problems (or any conflicts), so I'm not entirely sure how to resolve the conflict.   Any suggestions?

**Comment by tbl73** [comment]
The merged code has been pushed up.

**Pull request merged**
