### PR TITLE
'Done' button auto-advances to next page

### PR DESCRIPTION
**Pull request by WillNigel23**

### CODE REVIEW

**Review by benwbrum — APPROVED** [review]
This looks great.  Ready to test and merge.

**Comment by benwbrum** [comment]
If I hit "Done" from a transcription screen on Page 3, I am advanced to transcribing Page 4.  However, if I hit "Save" in the middle of transcribing Page 3, I am also advanced to Page 4.

The Save button should never redirect to a new page when clicked.  Both "Done" and "Approve" should advance to the next page.

See https://github.com/benwbrum/fromthepage/blob/development/app/views/transcribe/_save_buttons.html.slim for most of the permutations of the buttons and their state.

**Comment by benwbrum** [comment]
Save and Approve buttons work perfectly for both Optional Review and Review Required flows. 

In testing, I realized that there is another terminal state for a page which should auto-advance the page: marking a page Blank.  Let's add that as well.

**Comment by WillNigel23** [comment]
Changes made @benwbrum ready for test

**Pull request merged**
