### PR TITLE
If no pages need transcription, show incomplete pages for #2929 + CTA

### PR DESCRIPTION
**Pull request by benwbrum**
This is a partial solution to #2929

### CODE REVIEW

**Comment by saracarl** [comment]
This failed spec tests:
` 1) document sets checks document set breadcrumbs - work
     Failure/Error: expect(page).to have_content("No pages found")
       expected to find text "No pages found" in "ProjectsDashboard\nSigned In AseleanorCollaborator Dashboard\nYour Profile\nSign Out\nENEnglishEspañolPortuguês\nEdited Test Document Set 1\nMF1323.1197 Reel 32_0046-1\nReadAboutContentsVersionsHelp\nNo entries found\nSearchSearch in collection...\nCategories\nPeoplePlaces\nDocumentationBlogAboutTerms & ConditionsPrivacy PolicyContact Us\n© 2022 FromThePage. All rights reserved."
     # ./spec/features/document_sets_spec.rb:333:in `block (2 levels) in <top (required)>'`

**Comment by saracarl** [comment]
"Pages That Need Transcription" works in the work view -- it takes me to an incomplete page if there are none to be started but "Pages That Need Transcription" does not work in the collection view -- it tells me there are no pages need transcription.

**Comment by benwbrum** [comment]
This seems to behave correctly for document sets in interactive testing.
Screenshot from 2022-03-11 16-48-06

**Comment by kolking** [comment]
image

**Comment by kolking** [comment]
I've reworked it in accordance with your WSJ example:

image

**Comment by saracarl** [comment]
This looks good, but "pages needing transcription" should show incomplete pages (and implies it does), but doesn't:

image

**Pull request merged**
