### PR TITLE
#539 - Transcription conventions at collection level

### PR DESCRIPTION
**Pull request by tbl73**
Set up default transcription conventions at the collection level that can flow down to work level conventions.

### CODE REVIEW

**Comment by saracarl** [comment]
After you click the "revert" button and the transcription text reverts to the collection default, the button should be greyed out (like it is originally on a work with default collection transcription conventions).  It doesn't grey out, and that is confusing.

**Comment by tbl73** [comment]
Okay, I changed the button behavior.  (And the other issue was related to the Gemfile not being up to date in this branch.)

**Comment by saracarl** [comment]
Failed test:

Failures:

  1) collection related tasks reverts to collection level transcription conventions
     Failure/Error: expect(convention_work.transcription_conventions).to eq nil
       
       expected: nil
            got: "Work level transcription conventions"
       
       (compared using ==)
     # ./spec/features/collection_spec.rb:93:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 12.8 seconds (files took 2.36 seconds to load)
67 examples, 1 failure

Failed examples:

rspec ./spec/features/collection_spec.rb:81 # collection related tasks reverts to collection level transcription conventions

**Comment by saracarl** [comment]
Tests now failing with a different error:

Failures:

  1) collection related tasks reverts to collection level transcription conventions
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/images/uploaded/9/1724_thumb.jpg"
     # /home/saracarl/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
.
.
.
.
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 1 minute 56.62 seconds (files took 2.14 seconds to load)
67 examples, 1 failure

Failed examples:

rspec ./spec/features/collection_spec.rb:81 # collection related tasks reverts to collection level transcription conventions

**Comment by saracarl** [comment]
tests pass, yay.

**Pull request merged**
