### PR TITLE
#3597 Transcriber login redirect

### PR DESCRIPTION
**Pull request by symmetrically**

### CODE REVIEW

**Review by saracarl — CHANGES_REQUESTED** [review]
Ok, so this works as we asked, but we didn't do a good job defining what needs to happen.

If I'm a transcriber and I log in, I should go to my *dashboard*:
http://localhost:3000/dashboard/watchlist

(Sometimes that dashboard is empty, but we have text that sends them to the find a project page then.)

Apologies!

**Comment by symmetrically** [comment]
@saracarl I want to confirm that transcriber users are those who have owner & admin flag set to false. Right?

**Comment by symmetrically** [comment]
@saracarl I have done the required changes. Please check & let me know.

**Comment by saracarl** [comment]
Looks great, thank you.

**Pull request merged**
